version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@enkidevs/eslint-config-backend"
    versions:
    - 9.2.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
